CREATE DATABASE IF NOT EXISTS clinica_devjr
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE clinica_devjr;

CREATE TABLE IF NOT EXISTS medicos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  crm VARCHAR(20) NOT NULL,
  uf_crm CHAR(2) NOT NULL,
  especialidade VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_medicos_crm_uf UNIQUE (crm, uf_crm),
  CONSTRAINT chk_medicos_uf_crm CHECK (CHAR_LENGTH(uf_crm) = 2)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pacientes (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(120) NOT NULL,
  data_nascimento DATE NOT NULL,
  carteirinha VARCHAR(30) NOT NULL,
  cpf CHAR(11) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uq_pacientes_carteirinha UNIQUE (carteirinha),
  CONSTRAINT uq_pacientes_cpf UNIQUE (cpf),
  CONSTRAINT chk_pacientes_cpf_format CHECK (cpf REGEXP '^[0-9]{11}$')
) ENGINE=InnoDB;
